
<div class="head">
	<img class="img-head"
             
		src="/dinamic/logo/title-360.jpg">
</div>

<div class="titulo_categoria"><div class="titulo_item_a"><a href="">Correo y Chat</a></div></div>

<div class="item"><div class="titulo_item"> </div>

 <div class="item_i_o">
            <div class="text_item">
            <a href="/go?categoria=correo-chat&descripcion=Hotmail&link=http://www.hotmail.com">Hotmail</a><br/>
            </div>
        </div>
        <div class="item_p_o">
            <div class="text_item">
            <a href="/go?categoria=correo-chat&descripcion=Gmail&link=http://www.gmail.com">Gmail</a><br/>
            </div>
        </div>
        <div class="item_i_o">
            <div class="text_item">
            <a href="/go?categoria=correo-chat&descripcion=Yahoo&link=http://www.yahoo.com">Yahoo</a><br/>
            </div>
        </div>
<div class="text_item_li">
			<a href="/portalwap/">Volver </a>
</div>
</div>
<div class="verde"></div>



       <div class="item_legal">

                <div class="text_item">

                <a href="/go?categoria=legal&descripcion=Legal&link=/portalwap/legal">Legal</a><br/>

            </div>

        </div>