<div class="head">
    <img class="img-head"
         src="/dinamic/logo/title-360.jpg">
</div>
<div class="titulo_categoria"><div class="titulo_item_a"><a href="">Noticias</a></div></div>
<div class="item"><div class="titulo_item"> </div>
    <div class="item_i_o">
        <div class="text_item">
            <a href="/go?categoria=noticias&descripcion=Terra&link=http://m.terra.com.pe">Terra</a><br/>
        </div>
    </div>
    <div class="item_p_o">
        <div class="text_item">
            <a href="/go?categoria=noticias&descripcion=El Comercio&link=http://m.elcomercio.pe">El Comercio</a><br/>
        </div>
    </div>		 	
</div>
<div class="text_item_li">
    <a href="/portalwap">Volver </a>
</div>

<div class="verde"></div>
<div class="item_legal">
    <div class="text_item">
        <a href="/go?categoria=legal&descripcion=Legal&link=/portalwap/legal">Legal</a><br/>
    </div>
</div>