
<div class="head">
    <img class="img-head"

         src="/dinamic/logo/title-360.jpg">
</div>
<div class="item"><div class="titulo_item"> </div>
    <div id="contenedor"> 


        <div class="titulo_categoria"><div class="titulo_item_a"><a href="">Activa tu tono de espera</a></div></div>

        <div class="item"><div class="titulo_item"> </div>

        </div>
        <div class="verde"></div>

        <div id="publicidad">
            <a href="tel:*8889"><img src="/dinamic/logo/rbt.gif" width="100%" /></a><br/>
        </div>
<div class="text_item_li">
                <a href="/portalwap">Volver </a>
            </div>
        <div class="item_legal">

            <div class="text_item">

                <a href="/go?categoria=legal&descripcion=Legal&link=/portalwap/legal">Legal</a><br/>

            </div>

        </div>

    </div>
</div>


