<div class="head">
    <img class="img-head"

         src="/dinamic/logo/title-360.jpg">
</div>



<div class="titulo_categoria"><div class="titulo_item_a"><a href="">Redes Sociales</a></div></div>

<div class="item"><div class="titulo_item"> </div>
    <div class="item_i_o">
        <div class="text_item">
            <a href="/go?categoria=redes-sociales&descripcion=Facebook&link=https://m.facebook.com/">Facebook</a><br/>
        </div>
    </div>
    <div class="item_i_o">
        <div class="text_item">
            <a href="/go?categoria=redes-sociales&descripcion=Twitter&link=https://mobile.twitter.com/">Twitter</a><br/>
        </div>
    </div>
    <div class="item_p_o">
        <div class="text_item">
            <a href="/go?categoria=redes-sociales&descripcion=Google&link=https://www.google.com.pe">Google</a><br/>
        </div>
    </div>	
    <div class="item_p_o">
        <div class="text_item">
            <a href="/go?categoria=redes-sociales&descripcion=Correo y chat&link=/portalwap/correo-chat">Correo y chat</a><br/>
        </div>
    </div>	
    <div class="text_item_li">
        <a href="/portalwap">Volver </a>
    </div>
</div>
<div class="verde"></div>



<div class="item_legal">

    <div class="text_item">

        <a href="/go?categoria=legal&descripcion=Legal&link=/portalwap/legal">Legal</a><br/>

    </div>

</div>