<div class="head">
    <img class="img-head"
         src="<?= DINAMIC_URL?>logo/title-128.jpg">
</div>
<!-- <div class="taxes">
        <div class="text_item_ml">
                NAVEGA POR INTERNET en tu celular a solo S/.0.49 el MB. <a
                        href="go.php?link=tarifas.php">Ver más</a>
        </div>
</div>-->


<div class="spance-line"></div>

<div class="banner">
    <?php foreach (array(1, 2, 3, 4, 5, 6) as $i) : ?>
        <div  class="item-banner">
            <a href="/go?categoria=banner<?= $i ?>.<?= $this->SoapBanners[$i][0]['norder'] ?>&descripcion=<?= $this->SoapBanners[$i][0]['integrador'] ?>&link=<?= $this->SoapBanners[$i][0]['url'] ?>">
                <img class="img-banner" src="<?= DINAMIC_URL?>banner/basico128/<?= $this->SoapBanners[$i][0]['ImgBasico128'] ?>" alt="<?= $this->SoapBanners[$i][0]['titulo'] ?>" />
            </a>
        </div>
    <?php endforeach; ?>      
</div>

<!--/////////////////TOP LINK ///////////////////////////////7-->
<div id="section">   
    <div class="title-list">
        <div class="title-item">Top Link</div>
    </div>
    <div class="spance-line-item"></div>
    <?php foreach ($this->SoapLink as $item): ?>
    <div class="list">    
    <a class="list-link" href="/go?categoria=topLink&descripcion=<?= $item['descripcion'] ?>&link=<?= $item['url'] ?>">
    <?= $item['descripcion'] ?>
    </a>
    </div>
<?php endforeach; ?>
</div>
<!--/////////////////TOP LINK ///////////////////////////////7-->

<div id="section">   
    <div class="title-list">
        <div class="title-item">Servicios</div>
    </div>
    <div class="spance-line-item"></div>


    <?php foreach ($this->SoapServicio as $item): ?>
        <div class="list">
            <a class="list-link" href="/go?categoria=servicio&descripcion=<?= $item['descripcion'] ?>&link=<?= $item['url'] ?>"> 
                <?= $item['descripcion'] ?>
            </a>
        </div>
    <?php endforeach; ?>


</div>

<!-- música -->
<div id="section">   
    <div class="title-list">
        <div class="title-item">Musica</div>
    </div>
    <div class="title-clic">(Dando clic en la canción ya estás comprando! Costo S/. 4.75 )</div>
    <div class="spance-line-item"></div>

    <?php foreach ($this->SoapMusica as $item): ?>
        <div class="list">
            <a class="list-link"
               href="/go?categoria=musica&descripcion=<?= $item['titulo'] ?>&link=<?= $item["url"] ?>"><?= $item["titulo"] ?>
            </a>
        </div>
    <?php endforeach; ?>

</div>

<!-- section -->
<div id="section">   
    <div class="title-list">
        <div class="title-item">Juegos</div>
    </div>
    <div class="title-clic">(Dando clic al juego ya estás comprando! Costo S/. 7.91)</div>
    <div class="spance-line-item"></div>

    <?php foreach ($this->SoapJuego as $item): ?>
        <div class="list">
            <a class="list-link"
               href="/go?categoria=juego&descripcion=<?= $item['nombre'] ?>&link=<?= $item["url"] ?>"><?= $item["nombre"] ?>
            </a>
        </div>
    <?php endforeach; ?>
</div>



<div class="banner-second-section">
    <?php foreach (array(7, 8) as $i) : ?>
        <div  class="item-banner">
            <a href="/go?categoria=banner<?= $i ?>.<?= $this->SoapBanners[$i][0]['norder'] ?>&descripcion=<?= $this->SoapBanners[$i][0]['integrador'] ?>&link=<?= $this->SoapBanners[$i][0]['url'] ?>">
                <img class="img-banner" src="<?= DINAMIC_URL?>banner/basico128/<?= $this->SoapBanners[$i][0]['ImgBasico128'] ?>" alt="<?= $this->SoapBanners[$i][0]['titulo'] ?>" />
            </a>
        </div>
    <?php endforeach; ?> 
</div>

<!-- otros -->
<div id="section">
    <div class="spance-line-item"></div>    
    <?php foreach ($this->SoapText as $item): ?>
        <div class="list">
            <a class="list-link" href="/go?categoria=textLink&descripcion=<?= $item['alt'] ?>&link=<?= $item['url'] ?>">
                <?= $item['descripcion'] ?>
            </a>
        </div>
    <?php endforeach; ?>
</div>

<div class="banner-second-section">
    <?php foreach (array(9, 10) as $i) : ?>
        <div  class="item-banner">
            <a href="/go?categoria=banner<?= $i ?>.<?= $this->SoapBanners[$i][0]['norder'] ?>&descripcion=<?= $this->SoapBanners[$i][0]['integrador'] ?>&link=<?= $this->SoapBanners[$i][0]['url'] ?>">
                <img class="img-banner" src="<?= DINAMIC_URL?>banner/basico128/<?= $this->SoapBanners[$i][0]['ImgBasico128'] ?>" alt="<?= $this->SoapBanners[$i][0]['titulo'] ?>" />
            </a>
        </div>
    <?php endforeach; ?>
</div>


