<div class="head">
    <img class="img-head"
         src="<?= DINAMIC_URL?>logo/title-360.jpg">
</div>
<!-- <div class="taxes">
        <div class="text_item_ml">
                NAVEGA POR INTERNET en tu celular a solo S/.0.49 el MB. <a
                        href="go.php?link=tarifas.php">Ver más</a>
        </div>
</div>--> 


<div class="spance-line"></div>


<div class="banner">
        <?php foreach (array(1,2,3,4,5,6) as $i) : ?>
        <div class="box2">
            <a href="/go?categoria=banner<?= $i ?>.<?= $this->SoapBanners[$i][0]['norder'] ?>&descripcion=<?= $this->SoapBanners[$i][0]['integrador'] ?>&link=<?= $this->SoapBanners[$i][0]['url'] ?>">
                <img class="img-banner" src="<?= DINAMIC_URL?>banner/basico360/<?= $this->SoapBanners[$i][0]['ImgBasico360'] ?>" alt="<?= $this->SoapBanners[$i][0]['titulo'] ?>" />
            </a>
        </div>
    <?php endforeach; ?>      
</div>

<!--
<div class="banner">
    <?php foreach (array(1, 2, 3, 4, 5, 6) as $i) : ?>
        <div  class="box2">
            <div class="flex-container">
                <div class="flexslider">
                    <ul class="slides">
                        <?php foreach ($this->SoapBanners[$i] as $item): ?>
                            <li>
                                <a href="/go?categoria=banner<?= $i ?>.<?= $item['norder'] ?>&descripcion=<?= $item['integrador'] ?>&link=<?= $item['url'] ?>"><img class="img-banner" src="<?= DINAMIC_URL?>banner/basico360/<?= $item['ImgBasico360'] ?>" alt="<?= $item['titulo'] ?>" /></a>
                            </li>
                        <?php endforeach; ?>       
                    </ul>
                </div>
            </div>
        </div>
    <?php endforeach; ?> 
</div>-->

<!--/////////////////TOP LINK ///////////////////////////////7-->
<div style="clear: both;"></div>
<div id="section">
    <div class="title-list">
        <div class="title-item">Top Link</div>
    </div>
    <div class="spance-line-item"></div>
</div>
<?php foreach ($this->SoapLink as $item): ?>
    <div class="box"> <a href="/go?categoria=topLink&descripcion=<?= $item['descripcion'] ?>&link=<?= $item['url'] ?>">  <img class="img-banner" src="<?= DINAMIC_URL?>link/<?= $item['imagen'] ?>"></a>
    </div>
<?php endforeach; ?>
<!--/////////////////TOP LINK ///////////////////////////////7-->
<div style="clear: both;"></div>
<div id="section">
    <div class="title-list">
        <div class="title-item">Servicios</div>
        <div style="clear: both;"></div>
    </div>
    <div class="spance-line-item"></div>

    <?php foreach ($this->SoapServicio as $item): ?>
        <div class="list">
            <a class="list-link" href="/go?categoria=servicio&descripcion=<?= $item['descripcion'] ?>&link=<?= $item['url'] ?>"> 
                <?= $item['descripcion'] ?>
            </a>
        </div>
    <?php endforeach; ?>
</div>


<!-- música -->
<div id="section">   
    <div class="title-list">
        <div class="title-item">Musica</div>
        <div class="title-clic">(Dando clic en la canción ya estás comprando! Costo S/. 4.75 )</div>
        <!--        <div class="view-plus">
                <a class="" href="#vermas">
                <img class="img-plus" src="<?= DINAMIC_URL ?>/img/portalwap/basico360/icono_flecha.png">
                </a>
                </div>        -->
    </div>

</div>
<div class="spance-line-item"></div>
<table class="artist-photo">
    <tr>



        <?php foreach ($this->SoapMusica as $item): ?>
            <td class="artist">
                <div class="artist-text">
                    <div class="forma">
                        <img class="img-icono"
                             src="<?= DINAMIC_URL?>musica/basico360/<?= $item["img"] ?>">
                    </div>
                    <div class="title-img">
                        <a class="text-title"
                           href="/go?categoria=musica&descripcion=<?= $item['titulo'] ?>&link=<?= $item["url"] ?>"><?= $item["titulo"] ?>
                        </a>
                    </div>
                </div>
            </td>
        <?php endforeach; ?>    
    </tr>  
</table>
<!-- section -->
<div id="section">   
    <div class="title-list">
        <div class="title-item">Juego</div>
        <div class="title-clic">(Dando clic al juego ya estás comprando! Costo S/. 7.91)</div>
        <!--        <div class="view-plus">
                <a class="" href="#vermas">
                <img class="img-plus" src="<?= DINAMIC_URL ?>/img/portalwap/basico360/icono_flecha.png">
                </a>
                </div>        -->
    </div>

</div>
<div class="spance-line-item"></div>
<table class="artist-photo">
    <tr>

        <?php foreach ($this->SoapJuego as $item): ?>
            <td class="artist">
                <div class="artist-text">
                    <div class="">
                        <img class="img-icono"
                             src="<?= DINAMIC_URL?>juego/basico360/<?= $item["img"] ?>">
                    </div>
                    <div class="title-img">
                        <a class="text-title"
                           href="/go?categoria=juego&descripcion=<?= $item['nombre'] ?>&link=<?= $item["url"] ?>"><?= $item["nombre"] ?>
                        </a>
                    </div>
                </div>
            </td>
        <?php endforeach; ?>
    </tr>  
</table>



<div class="banner-second-section">

<div class="banner">
        <?php foreach (array(7,8) as $i) : ?>
        <div class="box2">
            <a href="/go?categoria=banner<?= $i ?>.<?= $this->SoapBanners[$i][0]['norder'] ?>&descripcion=<?= $this->SoapBanners[$i][0]['integrador'] ?>&link=<?= $this->SoapBanners[$i][0]['url'] ?>">
                <img class="img-banner" src="<?= DINAMIC_URL?>banner/basico360/<?= $this->SoapBanners[$i][0]['ImgBasico360'] ?>" alt="<?= $this->SoapBanners[$i][0]['titulo'] ?>" />
            </a>
        </div>
    <?php endforeach; ?>      
</div>
</div>
<div style="clear: both;"></div>



<?php foreach ($this->SoapText as $item): ?>
    <div class="center list-other box">
        <a class="list-link2" href="/go?categoria=textLink&descripcion=<?= $item['alt'] ?>&link=<?= $item['url'] ?>">
            <?= $item['descripcion'] ?>
        </a>
    </div>
<?php endforeach; ?>



<div class="banner">
        <?php foreach (array(9,10) as $i) : ?>
        <div class="box2">
            <a href="/go?categoria=banner<?= $i ?>.<?= $this->SoapBanners[$i][0]['norder'] ?>&descripcion=<?= $this->SoapBanners[$i][0]['integrador'] ?>&link=<?= $this->SoapBanners[$i][0]['url'] ?>">
                <img class="img-banner" src="<?= DINAMIC_URL?>banner/basico360/<?= $this->SoapBanners[$i][0]['ImgBasico360'] ?>" alt="<?= $this->SoapBanners[$i][0]['titulo'] ?>" />
            </a>
        </div>
    <?php endforeach; ?>      
</div>
<!--<div class="banner-second-section">
    <?php foreach (array(9, 10) as $i) : ?>
        <div  class="box2">
            <div class="flex-container">
                <div class="flexslider">
                    <ul class="slides">
                        <?php foreach ($this->SoapBanners[$i] as $item): ?>
                            <li>
                                <a href="/go?categoria=banner<?= $i ?>.<?= $item['norder'] ?>&descripcion=<?= $item['integrador'] ?>&link=<?= $item['url'] ?>"><img class="img-banner" src="<?= DINAMIC_URL?>banner/basico360/<?= $item['ImgBasico360'] ?>" alt="<?= $item['titulo'] ?>" /></a>
                            </li>
                        <?php endforeach; ?>       
                    </ul>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>-->


