
<div class="row-fluid login-wrapper">
	<a href="#">  
	</a>

	<div class="span12 box">
		<div class="content-wrap">
			<h6>Prueba </h6>
			<form action="/admin/auth/" method="post">
				<input class="span12" type="text" placeholder="Correo electrónico" name="email"> 
				<input class="span12" type="password" placeholder="Clave" name="clave"> 
				
				
				
				<input type="submit" class="btn-glow primary login" value="Ingresar"/>
			</form>
		</div>
	</div>
	<div class="span4 no-account">
		<!-- <p>¿No tienes una cuenta?</p>
		<a href="signup.html">Conoce más sobre Ringbacktone</a>-->
	</div>
</div>








