<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?= $this->headTitle() ?>
        <?= $this->headMeta() ?>
        <meta http-equiv="Pragma" content="no-cache">
            <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
                <meta http-equiv="expires" content="0">
                    <link rel="shortcut icon" href="<?php echo MEDIA_URL ?>favicon.ico" />
                    <!-- css -->
                    <link href="<?php echo MEDIA_URL ?>css/wap/general.css"
                          rel="stylesheet" />
                    <link href="<?php echo MEDIA_URL ?>css/wap/avanzado.css"
                          rel="stylesheet" />
                    <link href="<?php echo MEDIA_URL ?>css/wap/slider.css"
                          rel="stylesheet" />
                    <script type="text/javascript" src="<?php echo MEDIA_URL ?>js/jquery.min.js"></script>
                    <script type="text/javascript" src="<?php echo MEDIA_URL ?>js/slider.js"></script>
                    <script type="text/javascript" charset="utf-8">$(window).load(function () {
                            $('.flexslider').flexslider({controlsContainer: '.flex-container'});
                        });</script>
                    </head>
                    <body>
                        <div class="page">
                            <?= $this->layout()->content ?>
                            <div style="clear: both;"></div>
                            <script type="text/javascript" src="http://adscdn.axonix.com/js/axonix-tag.js">
                            </script><script>Axonix.getAd({version: "v1", type: 'js', adCode: 'ads-f24b4a72eaa34ad584b47414b07c1360', clickUrl: '', errorCallback: 'onError', targetBlank: 'false'});</script>



                            <script language="JavaScript" type="text/javascript"><!--
var eplDoc = document;
                                var eplLL = false;
                                var eS1 = 'us.img.e-planning.net';
                                var eplArgs = {iIF: 1, sV: schemeLocal() + "://ads.us.e-planning.net/", vV: "4", sI: "173ea", sec: "tecnologia", kVs: {}};
                                function eplCheckStart() {
                                    if (document.epl) {
                                        var e = document.epl;
                                        if (e.eplReady()) {
                                            return true;
                                        } else {
                                            e.eplInit(eplArgs);
                                            if (eplArgs.custom) {
                                                for (var s in eplArgs.custom) {
                                                    document.epl.setCustomAdShow(s, eplArgs.custom[s]);
                                                }
                                            }
                                            return e.eplReady();
                                        }
                                    } else {
                                        if (eplLL)
                                            return false;
                                        if (!document.body)
                                            return false;
                                        var eS2;
                                        var dc = document.cookie;
                                        var cookieName = ('https' === schemeLocal() ? 'EPLSERVER_S' : 'EPLSERVER') + '=';
                                        var ci = dc.indexOf(cookieName);
                                        if (ci != -1) {
                                            ci += cookieName.length;
                                            var ce = dc.indexOf(';', ci);
                                            if (ce == -1)
                                                ce = dc.length;
                                            eS2 = dc.substring(ci, ce);
                                        }
                                        var eIF = document.createElement('IFRAME');
                                        eIF.src = 'about:blank';
                                        eIF.id = 'epl4iframe';
                                        eIF.name = 'epl4iframe';
                                        eIF.width = 0;
                                        eIF.height = 0;
                                        eIF.style.width = '0px';
                                        eIF.style.height = '0px';
                                        eIF.style.display = 'none';
                                        document.body.appendChild(eIF);

                                        var eIFD = eIF.contentDocument ? eIF.contentDocument : eIF.document;
                                        eIFD.open();
                                        eIFD.write('<html><head><title>e-planning</title></head><bo' + 'dy></bo' + 'dy></html>');
                                        eIFD.close();
                                        var s = eIFD.createElement('SCRIPT');
                                        s.src = schemeLocal() + '://' + (eS2 ? eS2 : eS1) + '/layers/epl-41.js';
                                        eIFD.body.appendChild(s);
                                        if (!eS2) {
                                            var ss = eIFD.createElement('SCRIPT');
                                            ss.src = schemeLocal() + '://ads.us.e-planning.net/egc/4/1126c';
                                            eIFD.body.appendChild(ss);
                                        }
                                        eplLL = true;
                                        return false;
                                    }
                                }
                                eplCheckStart();
                                function eplSetAd(eID) {
                                    if (eplCheckStart()) {
                                        var opts = (eplArgs.sOpts && eplArgs.sOpts[eID]) ? eplArgs.sOpts[eID] : {};
                                        if (opts.custF) {
                                            document.epl.setCustomAdShow(eID, opts.custF);
                                        }
                                        document.epl.setSpace(eID, opts);
                                    } else {
                                        setTimeout('eplSetAd("' + eID + '");', 250);
                                    }
                                }
                                function eplAD4(eID, opts) {
                                    document.write('<div id="eplAdDiv' + eID + '"></div>');
                                    if (!opts)
                                        opts = {t: 1};
                                    if (!eplArgs.sOpts) {
                                        eplArgs.sOpts = {};
                                    }
                                    eplArgs.sOpts[eID] = opts;
                                    eplSetAd(eID);
                                }
                                function schemeLocal() {
                                    if (document.location.protocol) {
                                        protocol = document.location.protocol;
                                    } else {
                                        protocol = window.top.location.protocol;
                                    }
                                    if (protocol) {
                                        if (protocol.indexOf('https') !== -1) {
                                            return 'https';
                                        } else {
                                            return 'http';
                                        }
                                    }
                                }
//--></script>







                            <div class="footer">
                                <a class="legal" href="/go?categoria=legal&descripcion=Legal&link=/portalwap/legal">Legal</a>
                            </div>
                        </div>
                    </body>
                    </html>
