<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?= $this->headTitle() ?>
        <?= $this->headMeta() ?>
        <meta http-equiv="Pragma" content="no-cache">
        <meta http-equiv="expires" content="0">
        <link rel="shortcut icon" href="<?php echo MEDIA_URL ?>favicon.ico" />
        <!-- css -->
        <link href="<?php echo MEDIA_URL ?>css/wap/general.css"
              rel="stylesheet" />
        <link href="<?php echo MEDIA_URL ?>css/wap/basico360.css"
              rel="stylesheet" />
        <link href="<?php echo MEDIA_URL ?>css/wap/slider.css"
              rel="stylesheet" />
        <script type="text/javascript" src="<?php echo MEDIA_URL ?>js/jquery.min.js"></script>
        <script type="text/javascript" src="<?php echo MEDIA_URL ?>js/slider.js"></script>
        <script type="text/javascript" charset="utf-8">$(window).load(function() {
                $('.flexslider').flexslider({controlsContainer: '.flex-container'});
            });</script>

    </head>
    <body>
        <div class="page">

            <?= $this->layout()->content ?>
            <div style="clear: both;"></div>
            <script type="text/javascript" src="http://adscdn.axonix.com/js/axonix-tag.js">
                            </script><script>Axonix.getAd({version: "v1", type: 'js', adCode: 'ads-f24b4a72eaa34ad584b47414b07c1360', clickUrl: '', errorCallback: 'onError', targetBlank: 'false'});</script>
            <div class="footer">
                <a class="legal" href="/go?categoria=legal&descripcion=Legal&link=/portalwap/legal">Legal</a>
            </div>
        </div>
    </body>
</html>
