<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?= $this->headTitle() ?>
        <?= $this->headMeta() ?>
        <meta http-equiv="Pragma" content="no-cache">
        <meta http-equiv="expires" content="0">
        <link rel="shortcut icon" href="<?php echo MEDIA_URL ?>favicon.ico" />
        <!-- css -->
        <link href="<?php echo MEDIA_URL ?>css/wap/general.css"
              rel="stylesheet" />
        <link href="<?php echo MEDIA_URL ?>css/wap/basico128.css"
              rel="stylesheet" />
    </head>
    <body>
        <div class="page">

            <?= $this->layout()->content ?>

            <div class="footer">
                <a class="legal" href="/go?categoria=legal&descripcion=Legal&link=/portalwap/legal">Legal</a>
            </div>

        </div>
    </body>
</html>
